#
# Makefile for 'daq_trigger' directory
#
all:
#	pdflatex daq-esad.tex
#	acroread daq-esad.pdf

	pdflatex opman_master.tex
	evince opman_master.pdf

#	pdflatex master.tex
#	acroread master.pdf

clean:
	rm -f opman_master.aux
	rm -f opman_master.log
#	rm -f opman_master.pdf

#	rm -f master.aux
#	rm -f master.toc
#
